/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2e3132',
        'on-surface-variant': '#414754',
        'on-secondary-container': '#007327',
        'secondary-container': '#80f98b',
        'primary-fixed': '#d8e2ff',
        'surface': '#f8f9fa',
        'on-secondary': '#ffffff',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'on-surface': '#191c1d',
        'on-tertiary-fixed-variant': '#743500',
        'primary-fixed-dim': '#adc7ff',
        'surface-variant': '#e1e3e4',
        'on-secondary-fixed': '#002106',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#321300',
        'on-tertiary-container': '#fffbff',
        'on-primary-container': '#fefcff',
        'surface-container-highest': '#e1e3e4',
        'primary-container': '#0070ea',
        'tertiary-fixed-dim': '#ffb68a',
        'on-primary-fixed': '#001a41',
        'surface-tint': '#005bc0',
        'on-tertiary': '#ffffff',
        'surface-bright': '#f8f9fa',
        'tertiary-container': '#ba5900',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-dim': '#d9dadb',
        'background': '#f8f9fa',
        'on-secondary-fixed-variant': '#00531a',
        'outline': '#717786',
        'secondary': '#006e25',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f0f1f2',
        'surface-container-low': '#f3f4f5',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'on-background': '#191c1d',
        'on-primary-fixed-variant': '#004493',
        'inverse-primary': '#adc7ff',
        'tertiary': '#954500',
        'secondary-fixed': '#83fc8e',
        'tertiary-fixed': '#ffdbc8',
        'primary': '#0059bb',
        'secondary-fixed-dim': '#66df75',
        'outline-variant': '#c1c6d7',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}

